# 1 "data/maps/PetalburgGrove/scripts.pory"

# 2 "data/maps/PetalburgGrove/scripts.pory"
PetalburgGrove_MapScripts::
# 3 "data/maps/PetalburgGrove/scripts.pory"
	.byte 0

PetalburgGrove_WanderingWoman::
# 7 "data/maps/PetalburgGrove/scripts.pory"
	msgbox PetalburgGrove_WanderingWoman_Text_0
# 8 "data/maps/PetalburgGrove/scripts.pory"
	releaseall
	end


PetalburgGrove_WanderingWoman_Text_0:
# 7 "data/maps/PetalburgGrove/scripts.pory"
	.string "This place is so peaceful. I love seeing\n"
	.string "the Pokemon here.$"
